[package]
name = "hi-deps"
version = "0.1.0"
authors = ["yeahnoob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"

